---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2
addons:
  postgresql: '9.5'
before_install:
- gem install bundler -v 1.16.4
- source ${TRAVIS_BUILD_DIR}/tools/ci/create_db_user.sh
before_script: bundle exec rake spec:setup
